<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.chain_provider' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/User/ChainUserProvider.php';

return $this->privates['security.user.provider.concrete.chain_provider'] = new \Symfony\Component\Security\Core\User\ChainUserProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['fos_user.user_provider.username'] ?? $this->load('getFosUser_UserProvider_UsernameService.php'));
}, 1));
